#!/bin/bash

gnome-terminal -e "python3 displayService.py"
gnome-terminal -e "python3 homePage.py"
gnome-terminal -e "python3 cookbook.py"
gnome-terminal -e "python3 addRecipe.py"
gnome-terminal -e "python3 displayRecipeList.py"
gnome-terminal -e "python3 deleteRecipe.py"



